### ISSUE TITLE
제안 : Docsting style > pandas docsting style

### ISSUE THREAD

**Issue by DavidKimDY** [CoreDotToday/styleguide#1]
https://pandas.pydata.org/docs/development/contributing_docstring.html

**Comment by koorukuroo** [comment]
google-style 보다 numpy-style을 선호하시나 보네요!
https://queirozf.com/entries/python-docstrings-reference-examples

같이 논의해 보시죠~!

**Comment by jourmooney** [comment]
저희 하기로 했던 numpy-style이 pandas style이니 그대로 가시죠 ㅎㅎㅎ
