### ISSUE TITLE
Python Auto Formatter : Black 제안

### ISSUE THREAD

**Issue by jourmooney** [CoreDotToday/styleguide#2]
black이라는 autoformatter를 사용하면 어떨까요?
설정만 해두면 pycharm이나 vscode로 .py 파일을 저장 할 때 자동으로 Formatting 되어서 편리하더라고요.

https://www.daleseo.com/python-black/
https://black.readthedocs.io/en/stable/

**Comment by koorukuroo** [comment]
`pylint` 로 스타일 체크까지만 했는데 Black은 자동 맞춤까지 해주는 군요!
자동맞춤이 내가 원하지 않은 코드 형태로 잘못 자동 수정하면 어쩌나 싶은 마음에 한 번도 써보질 않았는데 요즘 많이들 활용하시나 보네요! 좋은 가이드 제안인 것 같습니다.

@DavidKimDY 님도 의견 부탁드려요~!

## Reference
- [파이썬 코드 스타일 이야기 - (1) Style Checker, Formatter들 구경하기](https://velog.io/@city7310/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%BD%94%EB%93%9C-%ED%8F%AC%EB%A7%A4%ED%84%B0-%EC%9D%B4%EC%95%BC%EA%B8%B0-5wjxdei9iv)
- [[Python] VS Code에서 Python lint 적용하기](https://icerabbit.tistory.com/98)

**Comment by DavidKimDY** [comment]
저도 좋을 것 같습니다~! 코드스타일을 맞추는데 드는 에너지 소모를 줄일 수 있을 것 같아요~! 그리고 스타일이 통일되면 코드를 읽는것도 더 편할 것 같습니다~!

**Comment by jourmooney** [comment]
약 일주일정도 사용해보니, 대부분의 경우에는 편리했지만 일부 가독성을 위해 작성해 놓은 코드가 자동 Formatting 되어 수정되는 경우도 있었습니다.

장점 : 협업 시 일관성 있는 코드 스타일에 대해 신경쓰지 않아도 됨.
단점 : 가독성을 위해 작성해 놓은 코드가 Black에서 지정해놓은 포맷으로  수정됨.

현재 저는 linter로 pycodestyle(PEP8), flake8, pylint를 사용 중이고, formatter로 black을 test 중입니다.

**Comment by jourmooney** [comment]
아! 그리고 Black은 Max Line Length가 88글자로 되어있는데, 이것도 기존 PEP8의 79글자와 차이가 있어 협의가 필요합니다.
Max Line Length는 vscode나 pycharm에서 수정 가능하며, linter에서도 협의되면 맞춰주면 편리하게 사용할 수 있을 것 같습니다

**Comment by koorukuroo** [comment]
- Max Line Length 89
- Autoformatter : `black`
